version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5437:5432'
    environment:
      POSTGRES_DB: nest-user-service-db
      POSTGRES_USER: tanthuann
      POSTGRES_PASSWORD: tanthuann
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: